### ISSUE TITLE
AuthorizationHeaderExtractor does not support DELETE http method

### ISSUE THREAD

**Issue by jeremyhahn** [dgrijalva/jwt-go#253] opened 2018-03-23 17:49 UTC
Shouldn't the library support authenticated requests to DELETE endpoints?

**Comment by dgrijalva** [comment] 2018-03-23 17:53
I believe it does. There's nothing in there that looks at the method.

**Comment by jeremyhahn** [comment] 2018-03-23 18:31
The comment indicates only GET and POST are supported. My local testing seems to confirm this.

https://github.com/dgrijalva/jwt-go/blob/24c63f56522a87ec5339cc3567883f1039378fdb/request/extractor.go#L34

**Comment by dgrijalva** [comment] 2018-03-23 19:17
It would appear you're right. This is actually caused by decisions made in the underlying library. `net/http` doesn't expect DELETE requests to have a body. A little googling suggest the behavior of bodies on DELETE requests isn't well defined. Many clients and servers ignore this. I'm not certain what the best action would be for this library.

See https://godoc.org/net/http#Request.ParseForm

**Comment by jeremyhahn** [comment] 2018-03-23 19:28
My use case is a simple delete to `/v1/resource/{id}` with no request body. The resource needs to be protected. I'd expect this to be a common use case. Using POST or PUT seems confusing at best or at worst, could cause conflicts with creates/updates. What is everyone else using for DELETE requests?

**Comment by ChadTaljaardt** [comment] 2018-03-23 19:29
There are use cases in which you would want to send a delete http verb to select multiple items for delete i think.

**Comment by dgrijalva** [comment] 2018-03-23 19:31
Without testing this myself, I expect the token would be found properly in a header or a parameter on the URL, but not in a post form body. Could you provide an example of what you're attempting that's not working?

**Comment by dgrijalva** [comment] 2018-03-23 19:34
I changed 'GET' to 'DELETE' in both test files and ran the tests. They passed just fine.

**Comment by dgrijalva** [comment] 2019-05-21 23:38
Closing issue. If you believe the issue is not resolved, please feel free to reopen and provide more information.

**Closed by dgrijalva** 2019-05-21 23:38 UTC
