### ISSUE TITLE
Non string Audience claims and VerifyAudience with `required` set to false

### ISSUE THREAD

**Issue by oponder** [dgrijalva/jwt-go#290] opened 2018-09-09 14:18 UTC
JWT tokens that have an array of strings in the audience claim can sneak through the `VerifyAudience` call when `required` is set to false

`VerifyAudience` tries to cast the `aud` claim to a string, and does not mind if it fails. When `m["aud"]` is not a string, `aud` will be set to `""`, and `VerifyAudience` will think there was no Audience claim in the token, and since `req` is set to false, it will return true.

https://github.com/dgrijalva/jwt-go/blob/06ea1031745cb8b3dab3f6a236daf2b0aa468b7e/map_claims.go#L13-L18

https://github.com/dgrijalva/jwt-go/blob/06ea1031745cb8b3dab3f6a236daf2b0aa468b7e/claims.go#L93-L102

This most likely affects the other `VerifyXXXX` methods too.

I don't know enough just about the spec to know what to do in this case, I just know that `Auth0` is returning these multiple audience tokens, and that's how I ran into this issue.

Here's a sample payload:

```
{
  "iss": "https://xxxxx.eu.auth0.com/",
  "sub": "github|xxxxx",
  "aud": [
    "xxxx",
    "https://xxxx.eu.auth0.com/userinfo"
  ],
  "iat": 1536500799,
  "exp": 1536501099,
  "azp": "xxxx",
  "scope": "openid profile email"
}
```

**Comment by oponder** [comment] 2018-09-09 14:46
I believe this here is the relevant part in the spec: https://tools.ietf.org/html/rfc7519#section-4.1.3

```
4.1.3.  "aud" (Audience) Claim

   The "aud" (audience) claim identifies the recipients that the JWT is
   intended for.  Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.  In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.  The
   interpretation of audience values is generally application specific.
   Use of this claim is OPTIONAL.
```

**Comment by source-creator** [comment] 2018-11-06 10:53
I can confirm this issue.

**Comment by JohnAmadeo** [comment] 2018-11-15 05:19
Running into the same scenario. Isn't the problem here that VerifyAudience doesn't correctly parse the "aud" claim when is it an array of strings (vs. a single string)? jwt-go just turns the array of audience tokens into the empty string ""

@oponder did you find a way to get around the issue? I'm also using Auth0 and I don't know how to solve it since it seems like Auth0 only returns multiple audience tokens, which jwt-go doesn't seem to support

**Comment by markuswustenberg** [comment] 2019-02-05 19:48
I got around it by using this ugly thing:

	claims := token.Claims.(jwt.MapClaims)
	parsedAud := ""
	switch aud := claims["aud"].(type) {
	case []interface{}:
		var auds []string
		for _, v := range aud {
			auds = append(auds, v.(string))
		}
		parsedAud = fmt.Sprintf("%v", auds)
	case interface{}:
		parsedAud = aud.(string)
	}
	if subtle.ConstantTimeCompare([]byte(parsedAud), []byte(expectedAud)) != 1 {
		return errors.Errorf("invalid audience (expected %v vs actual %v)", expectedAud, parsedAud)
	}

Note that the slice case needs to be first in the type switch, otherwise it matches `interface{}`. Also, I'm using `subtle.ConstantTimeCompare` like in the library, but I'm not sure why it's necessary. I guess that's why the package is called subtle…

**Comment by markuswustenberg** [comment] 2019-02-05 20:04
@dgrijalva would you merge a PR solving this issue in the above way?

**Comment by dgrijalva** [comment] 2019-05-21 22:52
This should be fixed in the upcoming v4. There's no way to fix it for `StandardClaims` without breaking the API. I'm on the fence about backporting the `MapClaims` version of the fix to v3 as quietly changes behavior.

**Closed by dgrijalva** 2019-05-21 22:52 UTC

**Comment by itinance** [comment] 2021-02-27 18:39
Any news about this? Just came across the same issue.
